server:
  port: 8081

spring:
  application:
    name: customer
  datasource:
    username: 'ErdiSyla'
    url: jdbc:postgresql://localhost:5500/fraud
    password: 'lightweightNoReaction123'
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'